trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true

  - task: Docker@2
    displayName: 'Build and push docker image'
    inputs:
      containerRegistry: $(ACR_CONNECTION_NAME)
      repository: 'tools-azurechat'
      command: 'buildAndPush'
      Dockerfile: 'src/dockerfile'
      buildContext: '$(Build.SourcesDirectory)/src'
      tags: |
        $(Build.BuildNumber)
        latest
